### ISSUE TITLE
Upgrading to 2.x is blocked by hard requirement for ramsey/uuid at 4.2.3

### ISSUE THREAD

**Issue by xtfer** [rudderlabs/rudder-php-sdk#15]
`ramsey/uuid` is locked to 4.2.3, but the current release is 4.7.x. We can't upgrade to 2.x as other packages require higher version of uuid (specifically, laravel requires ^4.7). I can only assume this is locked due to PHP 7.4 compatibility, but AFAIK that shouldn't be an issue since composer would prevent the upgrade on those packages for anyone on that environment (and 7.4 is EOL anyway).

In the meantime, 1.x is now throwing Deprecation notices in our integration environments.

Please unlock it. Thanks. :)

**Comment by bardisg** [comment]
Hello @xtfer,

Thank you foar raising this with us.

We will make this happen this asap for you!

**Comment by bardisg** [comment]
New version has been deployed and should resolve the issue.

**Comment by bardisg** [comment]
Hello @xtfer,

Please let me know if you are happy for me to close this issue.

Thanks
